force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Driver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ride__c/Ride__c.object-meta.xml
<CustomObject>
    <description>Shows which ride requests are being undertaken by an employee.</description>
    <label>Ride</label>
    <nameField>
        <displayFormat>RIDE-{0000}</displayFormat>
        <label>Ride Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ride__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Rides</relationshipLabel>
    <relationshipName>Rides</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ride__c/recordTypes/All.recordType-meta.xml
<RecordType>
    <fullName>All</fullName>
    <active>true</active>
    <description>Displays all fields.</description>
    <label>All</label>
</RecordType>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>The vehicle an employee/driver will use to conduct rideshares.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CheckVehicleForRideTriggerHandler.cls
public with sharing class CheckVehicleForRideTriggerHandler {
   
    public static void CheckForVehicle(List<Ride__c> allRides, List<Driver__c> allDrivers) {

        // Get all drivers, their vehicles and their rides
        Map<Id,Driver__c> drivers = new Map<Id,Driver__c>([SELECT Id,(SELECT Id FROM Vehicles__r),
                                                         (SELECT Id FROM Rides__r) 
                                                            FROM Driver__c 
                                                            WHERE Id IN :allDrivers]);

        Map<Id,Ride__c> rides = new Map<Id,Ride__c>([SELECT Id 
                                                    FROM Ride__c 
                                                    WHERE Id IN :allRides]);
        Integer index, i;
        for(i = 0; i < allDrivers.size(); i++) {
            // check if there is no vehicle 
            if (trigger.isInsert && drivers.get(allDrivers[i].Id).Vehicles__r.size() == 0) {
                if(drivers.get(allDrivers[i].Id).Rides__r.size() != 0) {   
                    index = i;
                }
            }     
        }                               
        // loop through all rides
        //for(Ride__c ride : allRides) {  
            rides.get(allRides[index].Id).Driver__c.addError('No vehicle found for ride.');
        //}  
    }
}