force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Driver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>The vehicle an employee/driver will use to conduct rideshares.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateCarTriggerHandler.cls
public with sharing class CreateCarTriggerHandler {
    
    public static void CreateNewCar(List<Driver__c> allDrivers) {
   
        List<Vehicle__c> vehicles = new List<Vehicle__c>();  

        //Get Related Vehicle Records For The Drivers  
        Map<Id,Driver__c> driversWithVehicles = new Map<Id,Driver__c>([SELECT Id,(SELECT Id FROM Vehicles__r) 
                                                                       FROM Driver__c 
                                                                       WHERE Id IN :allDrivers]);

        // Check for All the Drivers & If Any Drivers doesn't have the Vehicle, then ADD The Related Vehicle to that driver.  
        // Iterate Through Each Driver.  
        for(Driver__c driver : allDrivers) {  
            // Check if the driver already has a related vehicle.  
            if (driversWithVehicles.get(driver.Id).Vehicles__r.size() == 0) {  
            // If it doesn't have then, add Default vehicle  
            vehicles.add(new Vehicle__c(Make__c = 'test',
                                        Model__c = 'test',
                                        Year__c = 2000,
                                        Driver__c = driver.Id));  
            }        
        }  
        if (vehicles.size() > 0) {  
            insert vehicles;  
        }  
    }
}